name: Test

on: push

jobs:
  runscript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          chmod +x script.py
          ./script.py
          cat settings2.xml
          
